### ISSUE TITLE
Implement `std::error::Error` for error types

### ISSUE THREAD

**Issue by PonasKovas** [Rusty-Quartz/quartz_nbt#6]
Hello, thanks for this crate.

It's important that error types (such as `quartz_nbt::io::NbtIoError`) implement `Error`

**Comment by maddymakesgames** [comment]
All of our error types already implement `std::error::Error`

**Comment by Cassy343** [comment]
As Maddy said, all of our error types do implement `std::error::Error`. Keep in mind that, depending on the functionality you're using from the `Error` trait, you may need to `use std::error::Error;` in order to access our errors' implementations of the functions outlined in the trait.

**Comment by PonasKovas** [comment]
Oh shit, my brain isn't working. Not the first dumb issue I made today. Made it without even reading the errors I was getting...

My actual issue is this: could `From<quartz_nbt::io::NbtIoError>` be implemented for `std::io::Error`? This would be useful when reading/writing NBT in functions that do more IO and return `std::io::Result`, so the `?` try operator could be used on `quartz_nbt::io::read_nbt` and `quartz_nbt::io::write_nbt`.

**Comment by maddymakesgames** [comment]
It wouldn't really make sense for NbtIoError to be convertible into std::io::Error because NbtIoError is a superset of io::Error.
We have From<io::Error> implemented on NbtioError so you cause use that as your result's error, or you could use anyhow::Result.
