### ISSUE TITLE
Add support for indexmap for consistent key order

### ISSUE THREAD

**Issue by janispritzkau** [Rusty-Quartz/quartz_nbt#7]
Can be added as a crate feature, as `serde_json` does it with `preserve_order`.

https://docs.serde.rs/src/serde_json/map.rs.html
https://docs.rs/indexmap/latest/indexmap/

**Comment by janispritzkau** [comment]
I think it makes debugging or exploring NBT data structures a bit easier. The last project I did was counting all the items in chests, item frames, etc. in a world. While debugging it's a bit confusing to have the keys in a random order every time.

**Comment by Cassy343** [comment]
I didn't think about debugging - that's actually quite a salient point. That shouldn't be a very difficult feature to add so we'll keep it on our radar and get that taken care of soon.

**Comment by Cassy343** [comment]
Added this feature to version 0.2.6 which is now available, so closing issue.
