### ISSUE TITLE
quartz_nbt::snbt::parse edge-case

### ISSUE THREAD

**Issue by Vonr** [Rusty-Quartz/quartz_nbt#8]
```rs
quartz_nbt::snbt::parse(r#"{a:"1.0.0"}"#)
```
returns `Err(InvalidNumber)` rather than `Ok({a:1.0.0})`

Version: 0.2.6

**Comment by maddymakesgames** [comment]
Should be fixed by latest commit

**Comment by Vonr** [comment]
I'll leave this issue open for you to close at your own discretion, thank you!

**Comment by maddymakesgames** [comment]
Version 0.2.7 has been released with this bug fix
